# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metagraph.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='metagraph.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fmetagraph.proto\"\x07\n\x05\x42lock\"\x1a\n\tMetagraph\x12\r\n\x05\x62ytes\x18\x01 \x01(\x0c\x32.\n\x0fMetagraphServer\x12\x1b\n\x03Get\x12\x06.Block\x1a\n.Metagraph\"\x00\x62\x06proto3'
)




_BLOCK = _descriptor.Descriptor(
  name='Block',
  full_name='Block',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=26,
)


_METAGRAPH = _descriptor.Descriptor(
  name='Metagraph',
  full_name='Metagraph',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bytes', full_name='Metagraph.bytes', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=54,
)

DESCRIPTOR.message_types_by_name['Block'] = _BLOCK
DESCRIPTOR.message_types_by_name['Metagraph'] = _METAGRAPH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Block = _reflection.GeneratedProtocolMessageType('Block', (_message.Message,), {
  'DESCRIPTOR' : _BLOCK,
  '__module__' : 'metagraph_pb2'
  # @@protoc_insertion_point(class_scope:Block)
  })
_sym_db.RegisterMessage(Block)

Metagraph = _reflection.GeneratedProtocolMessageType('Metagraph', (_message.Message,), {
  'DESCRIPTOR' : _METAGRAPH,
  '__module__' : 'metagraph_pb2'
  # @@protoc_insertion_point(class_scope:Metagraph)
  })
_sym_db.RegisterMessage(Metagraph)



_METAGRAPHSERVER = _descriptor.ServiceDescriptor(
  name='MetagraphServer',
  full_name='MetagraphServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=56,
  serialized_end=102,
  methods=[
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='MetagraphServer.Get',
    index=0,
    containing_service=None,
    input_type=_BLOCK,
    output_type=_METAGRAPH,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_METAGRAPHSERVER)

DESCRIPTOR.services_by_name['MetagraphServer'] = _METAGRAPHSERVER

# @@protoc_insertion_point(module_scope)
